#!/bin/sh

# This is an indication as to what needs to be done when installing a new system, after
# following the install guide and chrooting

echo "Do not run this as a script! This is only intended as a reference" >&2
exit 1

ln -sf /usr/share/zoneinfo/Europe/Oslo /etc/localtime
hwclock --systohc
vim /etc/locale.gen 
locale-gen 
vim /etc/locale.conf
vim /etc/vconsole.conf
vim /etc/hostname
vim /etc/hosts 
passwd
grub-install --target=x86_64-efi --efi-directory=/efi/ --bootloader-id=GRUB
blkid /dev/nvme0n1p5
vim /etc/default/grub 
grub-mkconfig -o /boot/grub/grub.cfg
useradd -m amund
passwd amund
visudo
sudo usermod -aG wheel amund
sudo usermod -aG docker amund
git clone git@github.com/Amund211/dotfiles .dotfiles
sudo systemctl enable --now NetworkManager
./install-dotfiles 
mkdir stuff screenshots downloads tmp
git clone https://github.com/vivien/i3blocks-contrib
cd i3blocks-contrib/
cd cpu_usage2/
make
cd ..
cd bandwidth2
make
scp minitrue:/etc/X11/xorg.conf.d/30* .
scp minitrue:/etc/X11/xorg.conf.d/00* minitrue:/etc/X11/xorg.conf.d/50* .
sudoedit /etc/sysctl.conf
for i in {0..5}; do ./curl.sh make-triggered; done
for i in {0..5}; do ./curl.sh make-not-triggered; done
for i in {0..5}; do ./curl.sh make-empty; done
docker-full exec ignite-api python manage.py migrate
docker-full exec ignite-api python manage.py index_data
git clone git@github.com:Amund211/xbanish
cd xbanish/
make
sudo make install
sudo usermod -aG plugdev amund
sudo systemctl enable --now sshd.socket
git clone https://aur.archlinux.org/minecraft-launcher.git
cd minecraft-launcher/
makepkg -si
cd ..
git clone https://aur.archlinux.org/openrazer.git
cd openrazer/
makepkg -si
sudoedit /etc/ssh/sshd_config 
sudoedit /etc/mkinitcpio.conf 
