#!/bin/sh

# This is an indication as to what needs to be done when installing a new system, after
# following the install guide and chrooting

echo "Do not run this as a script! This is only intended as a reference" >&2
exit 1

# Configs
rm /home/amund.bash_profile
vim /etc/locale.conf
vim /etc/vconsole.conf
vim /etc/hostname
vim /etc/hosts
vim /etc/default/grub
vim /etc/ssh/sshd_config
vim /etc/mkinitcpio.conf
vim /etc/sysctl.conf
vim /etc/locale.gen
somehow_get /etc/X11/xorg.conf.d/  # Input configs like touchpad settings or mouse accel
somehow_get bin pics programming .scripts .gitconfig
visudo

# GRUB
grub-install --target=x86_64-efi --efi-directory=/efi/ --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg

# User account
useradd -m amund
passwd amund
sudo usermod -aG wheel amund
sudo usermod -aG docker amund
sudo usermod -aG plugdev amund

# Misc
locale-gen
passwd
ln -sf /usr/share/zoneinfo/Europe/Oslo /etc/localtime
hwclock --systohc

# i3blocks
git clone https://github.com/vivien/i3blocks-contrib
cd i3blocks-contrib/
cd cpu_usage2/
make
cd ..
cd bandwidth2
make

# Dotfiles
git clone git@github.com/Amund211/dotfiles .dotfiles
./install-dotfiles
mkdir stuff screenshots downloads tmp

# Systemd
sudo systemctl enable --now systemd-timesyncd.service
sudo systemctl enable --now sshd.socket
sudo systemctl enable --now NetworkManager

# More applications
git clone git@github.com:Amund211/xbanish
cd xbanish/
make
sudo make install
cd ..
git clone https://aur.archlinux.org/minecraft-launcher.git
cd minecraft-launcher/
makepkg -si
cd ..
git clone https://aur.archlinux.org/openrazer.git
cd openrazer/
makepkg -si

# Work stuff
for i in {0..5}; do ./curl.sh make-triggered; done
for i in {0..5}; do ./curl.sh make-not-triggered; done
for i in {0..5}; do ./curl.sh make-empty; done
docker-full exec ignite-api python manage.py migrate
docker-full exec ignite-api python manage.py index_data
